apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app: web
spec:
  containers:
    - name: web-container
      image: 207567758913.dkr.ecr.eu-west-2.amazonaws.com/kubernetesproject-web:latest
      ports:
        - containerPort: 80
